### ISSUE TITLE
Unable to `npm run start` - 'Unable to compile TypeScript'

### ISSUE THREAD

**Issue by MartinDM** [bonnie/udemy-ADVANCED-REACT-TESTING#1] opened 2021-10-06 15:23 UTC
Unfortunately I seem to have fallen at the first hurdle with this course :(

On running `npm run start`, having followed the steps in the README and installed the dependencies, I'm getting the following TS errors:
![image](https://user-images.githubusercontent.com/7467069/136233622-f48edd94-0f04-4333-b824-6a6192e04a9d.png)

**'Unable to compile TypeScript'**
Node version 14
![image](https://user-images.githubusercontent.com/7467069/136234086-064e948d-88e1-46fe-ad81-d48568181483.png)

Any pointers on this please as keen to get on with the material! Thanks.

**Comment by bonnie** [comment] 2021-10-07 16:48
I have updated the dependencies for the server to include `ts-node`; it works on my machine when I changed my node version to 14.8.0. Even though I'm not certain this is the cause of your issue, could you remove your `node_modules` directory and `package-lock.json`, run `npm install` again and let me know how it goes? 

Thanks!

**Comment by bonnie** [comment] 2021-10-11 16:23
Hi, @MartinDM, just checking in. Have you been able to get the server running on your machine? 

Cheers,
Bonnie

**Comment by MartinDM** [comment] 2021-10-12 08:11
Thanks for following up.
On first few goes, unfortunately no, but ran out of time to troubleshoot so will update you once I've had another run at this,  Bonnie with the outcome :)

**Comment by dramoslance** [comment] 2021-10-13 06:16
Hi @bonnie , I'm getting the same error while trying to run the server.

![image](https://user-images.githubusercontent.com/15838902/137077400-c6949e23-dd31-4848-99dd-82f91aba24ff.png)

**Comment by bonnie** [comment] 2021-10-14 05:18
Thanks for writing in, @dramoslance ! Could I get the full output of `npm start` please, preferably in text form (not screenshot)?

**Comment by dramoslance** [comment] 2021-10-14 05:22
Okay @bonnie,

`D:\Google Drive\Estudio\Testing\React\udemy-ADVANCED-REACT-TESTING\base-app\server\node_modules\ts-node\src\index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/route-methods/shows.ts:55:63 - error TS2571: Object is of type 'unknown'.

55     return res.status(500).json({ message: `could not hold: ${e.message}` });
                                                                 ~
src/route-methods/shows.ts:74:47 - error TS2571: Object is of type 'unknown'.

74       .json({ message: `could not purchase: ${e.message}` });
                                                 ~
src/route-methods/shows.ts:90:51 - error TS2571: Object is of type 'unknown'.

90       .json({ message: `could not release hold: ${e.message}` });
                                                     ~
src/route-methods/shows.ts:107:9 - error TS2801: This condition will always return true since this 'Promise<import("D:/Google Drive/Estudio/Testing/React/udemy-ADVANCED-REACT-TESTING/base-app/shared/types").Reservation | null>' is always defined.

107     if (getReservationById(purchaseIdNumber)) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/route-methods/shows.ts:107:9
    107     if (getReservationById(purchaseIdNumber)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Did you forget to use 'await'?
src/route-methods/shows.ts:114:51 - error TS2571: Object is of type 'unknown'.

114       .json({ message: `could not release hold: ${e.message}` });
                                                      ~

    at createTSError (D:\Google Drive\Estudio\Testing\React\udemy-ADVANCED-REACT-TESTING\base-app\server\node_modules\ts-node\src\index.ts:513:12)
    at reportTSError (D:\Google Drive\Estudio\Testing\React\udemy-ADVANCED-REACT-TESTING\base-app\server\node_modules\ts-node\src\index.ts:517:19)
    at getOutput (D:\Google Drive\Estudio\Testing\React\udemy-ADVANCED-REACT-TESTING\base-app\server\node_modules\ts-node\src\index.ts:752:36)
    at Object.compile (D:\Google Drive\Estudio\Testing\React\udemy-ADVANCED-REACT-TESTING\base-app\server\node_modules\ts-node\src\index.ts:968:32)
    at D:\Google Drive\Estudio\Testing\React\udemy-ADVANCED-REACT-TESTING\base-app\server\node_modules\ts-node\src\esm.ts:99:38
    at Generator.next (<anonymous>)
    at D:\Google Drive\Estudio\Testing\React\udemy-ADVANCED-REACT-TESTING\base-app\server\node_modules\ts-node\dist\esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Google Drive\Estudio\Testing\React\udemy-ADVANCED-REACT-TESTING\base-app\server\node_modules\ts-node\dist\esm.js:4:12)
    at transformSource (D:\Google Drive\Estudio\Testing\React\udemy-ADVANCED-REACT-TESTING\base-app\server\node_modules\ts-node\dist\esm.js:72:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! classy-restaurant-server@1.0.0 start: `node --loader ts-node/esm src/server.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the classy-restaurant-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Deiby Ramos\AppData\Roaming\npm-cache\_logs\2021-10-14T05_21_46_172Z-debug.log`

**Comment by bonnie** [comment] 2021-10-14 05:32
Thank you @dramoslance ! I've uploaded a new commit -- could you try again please and let me know how it goes?

**Comment by dramoslance** [comment] 2021-10-15 06:50
Hi @bonnie,

I tried after your commit -- the error was solved.

But, a new error regarding the experimental loader raise (it is about the commonjs) while importing the json package from express.

I solved it by using a new way to import that package:

`import json from 'express';`

Thanks,

Deiby

**Comment by bonnie** [comment] 2021-10-15 17:38
Hi, @dramoslance , 

Thanks for reporting back! Can you tell me more about the `import json from 'express';` fix? Was the issue at [this line](https://github.com/bonnie/udemy-ADVANCED-REACT-TESTING/blob/af17966f79484ccbdcff6b36bdd1507552d13ccf/base-app/server/src/server.ts#L5) in server.ts? 

```
import express, { json } from 'express';
```

Since the default export for `'express'` is the `express` object, I'm surprised that renaming the import to `json` wouldn't mess up the express functionality. Or did you import twice from `'express'` like this: 

```
import express from 'express';
import json from 'express';
```

and you're using, say, `json.json` to access the `json` object from express? 

Cheers,
Bonnie

**Comment by dramoslance** [comment] 2021-10-15 21:43
Hi @bonnie,

Yes I used this fix:

```
import express from 'express';
import json from 'express';
```
[to this line](https://github.com/bonnie/udemy-ADVANCED-REACT-TESTING/blob/af17966f79484ccbdcff6b36bdd1507552d13ccf/base-app/server/src/server.ts#L5)

**Comment by bonnie** [comment] 2021-10-16 03:31
I assume you would then have to update [this line](https://github.com/bonnie/udemy-ADVANCED-REACT-TESTING/blob/af17966f79484ccbdcff6b36bdd1507552d13ccf/base-app/server/src/server.ts#L48) to

```
app.use(json.json()); 
```

If so, I would prefer to eliminate the `import json from 'express';` line and simply write

```
app.use(express.json()); 
```

**Comment by bonnie** [comment] 2021-10-18 01:24
Closing this issue, but please reopen it if you can't get the server running with the latest commit, @MartinDM !

**Closed as completed** 2021-10-18 01:24 UTC
